### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by utopiaye** [pjz/micropython-wiegand#10]
Hello, Paul
Using the class you provided, I found that the same card returned different numbers after using the example you provided. Why?
The IO pin I use is io12 / io13
![微信图片_20200826193036](https://user-images.githubusercontent.com/5866954/91300771-69aa2f80-e7d6-11ea-966b-b1a96e12736e.jpg)
![image](https://user-images.githubusercontent.com/5866954/91300806-77f84b80-e7d6-11ea-946b-44d5bba36c07.png)

**Comment by pjz** [comment]
This often has to do with the quality of the reader and the shielding on the cable.
