### ISSUE TITLE
2 RFID Reader connection on ESP32

### ISSUE THREAD

**Issue by Guru-Solidz** [pjz/micropython-wiegand#11]
Hi
I wish to integrate 2 rfid wiegand readers with esp32.  the micropython-wiegand library works beautifully with 1 rfid reader, but when 2 rfid readers are connected, only one works.  could you let me know what needs to be done to make 2 rfid readers work with esp32 using this micropython-wiegand?

thanks

**Comment by pjz** [comment]
Since it uses IRQs for eventing, it should be fine, just make two Wiegand objects and set their pins and callbacks correctly.  You can perhaps debug by seeing if, when both are attached, each will work individually.

**Comment by Guru-Solidz** [comment]
Hi,
Thank you for the response.

both rfid readers are connected.  out of the two, the reader to which the first card is flashed, works.

the code is given below for your easy reference.  If you could help point out the mistake i am making, it would be very kind of you.
```python
import gc, time
from wiegand import Wiegand

rf1D0 = 12
rf1D1 = 13

rf2D0 = 10
rf2D1 = 11

i = 0
j = 0

def on_card_1(card_number, facility_code, cards_read, r='R1'):
    global i
    print ('card number = ', card_number)
    print ('facility Code = ', facility_code)
    card = int(facility_code) * 65535 + int(card_number) + facility_code
    print ("Reader = ", r)
    print ('card 1 = ' +  str(card) +  " Count = " + str(i))
    i = i + 1

def on_card_2(card_number, facility_code, cards_read, r='R2'):
    global j
    print ('card number = ', card_number)
    print ('facility Code = ', facility_code)
    card = int(facility_code) * 65535 + int(card_number) + facility_code
    print ("Reader = ", r)
    print ('card 2  = ' + str(card) +  " Count = " + str(j))
    j = j + 1


Wiegand(rf1D0, rf1D1, on_card_1)
Wiegand(rf2D0, rf2D1, on_card_2)
```

**Comment by Guru-Solidz** [comment]
Hi Paul,

First of all, Thank you for your reply.  I had responded to the same on
github, but couldn't receive a response, possibly because you had marked
the thread as closed.

Reproducing the same here for your reference.

My requirement is to connect 2 RFID readers (Wiegand 26 bit) to esp32 to
read the card number.  The wiegand class written by you works perfectly,
and with that, I am able to get data from 1 RFID reader, if only 1 is
connected and configured.  If 2 RFID readers are connected, only the 2nd
one provides the data, while the first RFID reader does not provide any
data.

I have tried the following:
1. from wiegand import Wiegand
    Wiegand(rfid1D0, rfid1D1, on_card)
    Wiegand(rfid2D0, rfid2D1, on_card)

The above code only provides the 2nd RFID reader's data.

2. I made two copies of the wiegand file.  (namely wiegand.py and
wiegand1.py, and inside wiegand1.py, i renamed the class Wiegand as WG)

from wiegand import Wiegand
from wiegand1 import WG

Wiegand(fid1D0, rfid1D1, on_card)
WG(fid2D0, rfid2D1, on_card)

In this case too, only the 2nd RFID reader (WG) provides the data, while
the first RFID reader does not provide any data.

If I comment out the WG, then the first RFID provides the data flawlessly.
(Code shown below)

################################

Wiegand(fid1D0, rfid1D1, on_card)
#WG(fid2D0, rfid2D1, on_card)

################################

I am unable to figure out how to make both RFID work simultaneously, maybe
due to my limited knowledge on the above.

Could you kindly help me point in the right direction, so that I can
resolve this issue.  I once again thank you for your help and support and
look forward to receiving your valuable reply at the earliest.
*_____________________________________________________________*
*Thanks*
*Guruprasad NK | *+91 98718 43210
Founder & CEO*  | **Solidz.IO*

**Comment by pjz** [comment]
Alright, I _may_ have found the issue. (note: I have no current hardware to test with, so I was just thinking through the code), which has to do with sharing/resetting timer interrupt callbacks.  Try again but with
```
Wiegand(fid1D0, rfid1D1, on_card, 0)
Wiegand(fid2D0, rfid2D1, on_card, 1)
```
I'm not positive it will work, but if not, I'm stumped as there's now no resources at all shared between objects.

**Comment by Guru-Solidz** [comment]
Hi Paul,
Thanks a ton for pointing me out in the right direction.

The following changes were made.

1. in the class Wiegand, the following changes were made, as underlined:
class Wiegand:
    def __init__(self, pin0, pin1, *timer,* callback):
        """
        pin0 - the GPIO that goes high when a zero is sent by the reader
        pin1 - the GPIO that goes high when a one is sent by the reader
        callback - the function called (with two args: card ID and
cardcount)
                   when a card is detected.  Note that micropython interrupt
                   implementation limitations apply to the callback!
        """
        self.pin0 = Pin(pin0, Pin.IN)
        self.pin1 = Pin(pin1, Pin.IN)
        self.callback = callback
        self.last_card = None
        self.next_card = 0
        self._bits = 0
        self.pin0.irq(trigger=Pin.IRQ_FALLING, handler=self._on_pin0)
        self.pin1.irq(trigger=Pin.IRQ_FALLING, handler=self._on_pin1)
        self.last_bit_read = None
        self.timer = Timer(*timer*)

2. Wiegand(WG_0_0, WG_0_1, *1,* on_card)

With these two changes, I am able to get the data from both RFID readers.

Once again, my sincere thanks for your timely support.

Wish you a great day ahead!
*_____________________________________________________________*
*Thanks*
*Guruprasad NK | *+91 98718 43210
Founder & CEO*  | **Solidz.IO*
