### ISSUE TITLE
issue in printing card id

### ISSUE THREAD

**Issue by Tejas-GS** [pjz/micropython-wiegand#5]
Hi Sir,
I am not able to print the card number and the facility number of my rfid .
I am getting my card id and facility number as 0.
I used that exmaple program with EM-18 card reader and esp32. 
plz hepl me ..
![2019-03-08-100708_1184x624_scrot](https://user-images.githubusercontent.com/48342749/54007878-0f548380-418a-11e9-8dea-ffb84a645542.png)
 ![2019-03-08-100729_1184x624_scrot](https://user-images.githubusercontent.com/48342749/54007879-0f548380-418a-11e9-8fcd-19e9c902b537.png)

**Comment by pjz** [comment]
re-open if needed.
