### ISSUE TITLE
From some readers it returns random data

### ISSUE THREAD

**Issue by iBobik** [pjz/micropython-wiegand#6]
With some readers I receive different data for the same tag:

This is log from repeately putting one specific tag to a chinese no-name reader 7304D2:

UID: 13911 facility: 0 card_number: 6955
UID: 27702 facility: 0 card_number: 13851
UID: 27814 facility: 0 card_number: 13907
UID: 13911 facility: 0 card_number: 6955
UID: 25622 facility: 0 card_number: 12811
UID: 13399 facility: 0 card_number: 6699
UID: 27814 facility: 0 card_number: 13907
UID: 27702 facility: 0 card_number: 13851
UID: 13911 facility: 0 card_number: 6955
UID: 27702 facility: 0 card_number: 13851
UID: 25622 facility: 0 card_number: 12811
UID: 13911 facility: 0 card_number: 6955
UID: 13911 facility: 0 card_number: 6955

Same tag but with reader IronLogic CP-Z:

UID: 4820 facility: 0 card_number: 2410
UID: 9452 facility: 0 card_number: 4726
UID: 9449 facility: 0 card_number: 4724
UID: 4820 facility: 0 card_number: 2410
UID: 4820 facility: 0 card_number: 2410
UID: 9449 facility: 0 card_number: 4724
UID: 4820 facility: 0 card_number: 2410
UID: 9704 facility: 0 card_number: 4852
UID: 4820 facility: 0 card_number: 2410
UID: 9449 facility: 0 card_number: 4724
UID: 4820 facility: 0 card_number: 2410
UID: 9449 facility: 0 card_number: 4724
UID: 0 facility: 0 card_number: 0
UID: 9449 facility: 0 card_number: 4724
UID: 4820 facility: 0 card_number: 2410

Tested multiple tags, results are similar.

Same tag and same readers works with this C library: https://github.com/monkeyboard/Wiegand-Protocol-Library-for-Arduino

**Comment by pjz** [comment]
A little analysis shows that the first batch is flipping bits in its report:

| Decimal | Binary |
| --- | --- |
| 6955 | `01101100101011`|
|13851 |`11011000011011` |
|13907 |`11011001010011` |
|12811|`11001000001011` |
|6699|`01101000101011`|

What was the actual number of the card, BTW?

Both batches look to be having timing problems - this could be because of the reader, or because the interrupts aren't being serviced quickly enough (eg. your cpu is overloaded).  Reading these things is fairly timing sensitive, so it's possible that an embedded CPU running something as interpreted as micropython is just not fast enough.

**Comment by iBobik** [comment]
I run it on ESP8266 and tested it on clean system where nothing else runs.

Could it be theoretically solved by binding C library?



28. 5. 2019 v 23:34, Paul Jimenez <notifications@github.com>:

**Comment by iBobik** [comment]
And btw why some readers works? Is it possible that they send data by different speed?

**Comment by utopiaye** [comment]
I have the same problem

**Comment by pjz** [comment]
I really don't know; it may be hardware dependent.  This code just bitbangs its hardest.  If you figure it out, I'm open to PRs.

**Comment by iBobik** [comment]
I end up with this dual band reader which works well:
Zoneway U-P001EM

https://eletur.cz/ctecka-zoneway-up001em-rfid-mifare

**Comment by Pegasus-India** [comment]
Hi,
where you able to resolve this?  facing the same issue.  Using ESP32.

4 out of every 10 scan of the card, provides a wrong number.

**Comment by iBobik** [comment]
I bought better readers and were more careful about quality of the
connection. Used shielded CAT cable when possible, used twisted pairs
correctly etc.


Honza Pobořil


2. 6. 2022 8:16:18, Pegasus-India ***@***.***> napsal:
