### ISSUE TITLE
access control system RFID

### ISSUE THREAD

**Issue by lasuridze** [pjz/micropython-wiegand#8]
hello i have access control system witch work access remote Orange Pi Zero  D0 D1 COM GLED.
i work with to node js and python both get in data from access control RFID reader 
Python: micropython-wiegand
Node Js: wiegand-node
Access control model: tivdio ac800 how have output Wiegand 26 and Wiegand 34
Orange Pi Zero
this mode: https://ibb.co/hKC1Xs5
After a while stop Received information.
RFID not communication with Pi
Pi Receives and issues data but not from RFID 
I checked the contacts and checked program but not result 
i change new Orange PI and new RIFD reader but not result
What do you prefer what to do?

**Comment by pjz** [comment]
I think that has nothing to do with this code, which only listens to and interprets wiegand data.  Sorry, best of luck.
